### ISSUE TITLE
Check access token authentication method

### ISSUE THREAD

**Issue by shillner** [shillner/unleash-scm-provider-git#12]
There is also the possibility to access git repositories using access tokens but the provider is not aware of this method and fails with an exception.

This issue was filed under the [unleash-maven-plugin (issue #97](https://github.com/shillner/unleash-maven-plugin/issues/97).

**Comment by jodastephen** [comment]
I've found the maven-release-plugin on Windows uses the git credential manager for windows (using an HTTPS connection). Unleash does not seem to do this, and without the access token method as an alternative I have no ability to use unleash sadly.
