### ISSUE TITLE
Git - Committing local changes extremely slow after tag

### ISSUE THREAD

**Issue by gustafg** [shillner/unleash-scm-provider-git#14]
We have a repo with lots of big files, suspect this is the reason. Committing as part of the tag process takes 2 minutes in this repo (which in turn cause the release process to be as slow as using Maven release plugin which has other problems but not these).

After some debugging I found that the problem disappears when applying this patch:
```
diff --git a/src/main/java/com/itemis/maven/plugins/unleash/scm/providers/ScmProviderGit.java b/src/main/java/com/itemis/maven/plugins/unleash/scm/providers/ScmProviderGit.java
index 476c942..f7bb103 100644
--- a/src/main/java/com/itemis/maven/plugins/unleash/scm/providers/ScmProviderGit.java
+++ b/src/main/java/com/itemis/maven/plugins/unleash/scm/providers/ScmProviderGit.java
@@ -314,13 +314,13 @@ public class ScmProviderGit implements ScmProvider {

     // commit all added changes
     CommitCommand commit = this.git.commit().setMessage(request.getMessage()).setCommitter(this.personIdent);
-    if (request.commitAllChanges()) {
-      commit.setAll(true);
-    } else {
-      for (String path : request.getPathsToCommit()) {
-        commit.setOnly(path);
-      }
-    }
+    // if (request.commitAllChanges()) {
+    //   commit.setAll(true);
+    // } else {
+    //   for (String path : request.getPathsToCommit()) {
+    //     commit.setOnly(path);
+    //   }
+    // }
```
I suppose there is an underlying problem in JGit (for us the problem is related to `commit.setAll(true)`), either way, I'm not sure of the purpose of this code, it seems redundant on the lines just before it doing the equivallent of `git add`. Can I send a PR to remove it or have I misunderstood something?

**Comment by shillner** [comment]
Hi, I haven't had a look into it yet but yes, send your PR and then I'll see what happens there.
In addition it would be ideal if you could provide a test repo which is affected by that problem. Even if the commit then takes 10 seconds instead of 0.5. It just has to be a measurable amount of additional work to see the effect.
