### ISSUE TITLE
Algorithm negotiation fail with github using ssh

### ISSUE THREAD

**Issue by andreasaronsson** [shillner/unleash-scm-provider-git#15]
I get a failure when doing a release. 
I suspect this is due to jgit using an older Jsch that is not up to date with https://githubengineering.com/crypto-removal-notice/

Bumping jgit could fix this issue. Currently 4.3.0.201604071810-r is used. 
Latest at the time of this writing is v5.0.2.201807311906-r
https://search.maven.org/artifact/org.eclipse.jgit/org.eclipse.jgit/5.0.2.201807311906-r/jar

`
Caused by: com.jcraft.jsch.JSchException: Algorithm negotiation fail
    at com.jcraft.jsch.Session.receive_kexinit (Session.java:559)
    at com.jcraft.jsch.Session.connect (Session.java:299)
    at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession (JschConfigSessionFactory.java:116)
    at org.eclipse.jgit.transport.SshTransport.getSession (SshTransport.java:136)
    at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init> (TransportGitSsh.java:264)
    at org.eclipse.jgit.transport.TransportGitSsh.openFetch (TransportGitSsh.java:162)
    at org.eclipse.jgit.api.LsRemoteCommand.execute (LsRemoteCommand.java:198)
    at org.eclipse.jgit.api.LsRemoteCommand.call (LsRemoteCommand.java:159)
    at com.itemis.maven.plugins.unleash.scm.providers.ScmProviderGit.hasTag (ScmProviderGit.java:634)
`

Here is a fix in bazel 
https://bazel-review.googlesource.com/c/bazel/+/43610

and another one pointing in this direction
https://groups.google.com/forum/#!topic/repo-discuss/AMVDwTIeDJw/discussion

Edit: I tried bumping jgit to 4.10.x but I get the following error when releasing:

`
Caused by: java.lang.NoClassDefFoundError: com/jcraft/jsch/ConfigRepository
    at java.lang.Class.getDeclaredConstructors0 (Native Method)
    at java.lang.Class.privateGetDeclaredConstructors (Class.java:2671)
    at java.lang.Class.getDeclaredConstructors (Class.java:2020)
    at org.jboss.weld.annotated.slim.backed.SecurityActions.getDeclaredConstructors (SecurityActions.java:57)
`

**Comment by shillner** [comment]
Hi, Ive upgraded JGit to the newest version and verified that SSH access still works for me in conjunction with an SSH agent setup.
Can you try to build and use the current version of the git provider and tell me if this fixed your issue? Thanks.

**Comment by andreasaronsson** [comment]
I tried with 5.0.2.201807311906-r but got the same error as with 4.10.x. It is not unlikely I made an error in my environment. I will make a new attempt as soon as I can and post back again. Thanks for the attention!

**Comment by andreasaronsson** [comment]
After adding the 5.0 version I get the following dependency:tree
`
[INFO] Building Unleash SCM Provider Git 2.2.1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ unleash-scm-provider-git ---
[INFO] com.itemis.maven.plugins:unleash-scm-provider-git:jar:2.2.1
[INFO] +- com.jcraft:jsch.agentproxy.jsch:jar:0.0.9:compile
[INFO] |  +- com.jcraft:jsch:jar:0.1.49:compile
[INFO] |  \- com.jcraft:jsch.agentproxy.core:jar:0.0.9:compile
[INFO] +- com.jcraft:jsch.agentproxy.pageant:jar:0.0.9:compile
[INFO] |  +- net.java.dev.jna:jna:jar:4.1.0:compile
[INFO] |  \- net.java.dev.jna:jna-platform:jar:4.1.0:compile
[INFO] +- com.jcraft:jsch.agentproxy.sshagent:jar:0.0.9:compile
[INFO] +- com.jcraft:jsch.agentproxy.usocket-jna:jar:0.0.9:compile
[INFO] +- junit:junit:jar:4.12:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] +- org.mockito:mockito-all:jar:1.10.19:test
[INFO] +- org.eclipse.jgit:org.eclipse.jgit:jar:5.0.2.201807311906-r:compile
[INFO] |  +- com.jcraft:jzlib:jar:1.1.1:compile
[INFO] |  +- com.googlecode.javaewah:JavaEWAH:jar:1.1.6:compile
[INFO] |  +- org.apache.httpcomponents:httpclient:jar:4.5.2:compile
[INFO] |  |  +- org.apache.httpcomponents:httpcore:jar:4.4.4:compile
[INFO] |  |  +- commons-logging:commons-logging:jar:1.2:compile
[INFO] |  |  \- commons-codec:commons-codec:jar:1.9:compile
[INFO] |  \- org.slf4j:slf4j-api:jar:1.7.2:compile
[INFO] +- org.slf4j:slf4j-simple:jar:1.7.2:test
[INFO] \- com.itemis.maven.plugins:unleash-scm-provider-api:jar:2.6.0:compile
[INFO]    +- javax.enterprise:cdi-api:jar:1.2:compile
[INFO]    |  +- javax.el:javax.el-api:jar:3.0.0:compile
[INFO]    |  +- javax.interceptor:javax.interceptor-api:jar:1.2:compile
[INFO]    |  \- javax.inject:javax.inject:jar:1:compile
[INFO]    +- org.apache.commons:commons-lang3:jar:3.4:compile
[INFO]    \- com.google.guava:guava:jar:19.0:compile

`

Which points to jsch 1.49. I get the impression at least 1.51 is needed. This is confusing. 

I still get the error after building against 5.0.2.201807311906-r, adding it to the dependency section for the unleash-maven-plugin and then trying to do a release. Not sure what to try next.

**Comment by shillner** [comment]
There must be something wrong since I'm getting the following dependency tree (jsch version 1.54):

[INFO] Building Unleash SCM Provider Git 2.2.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ unleash-scm-provider-git ---
[INFO] com.itemis.maven.plugins:unleash-scm-provider-git:jar:2.2.1-SNAPSHOT
[INFO] +- com.jcraft:jsch:jar:0.1.54:compile
[INFO] +- com.jcraft:jsch.agentproxy.jsch:jar:0.0.9:compile
[INFO] |  \- com.jcraft:jsch.agentproxy.core:jar:0.0.9:compile
[INFO] +- com.jcraft:jsch.agentproxy.pageant:jar:0.0.9:compile
[INFO] |  +- net.java.dev.jna:jna:jar:4.1.0:compile
[INFO] |  \- net.java.dev.jna:jna-platform:jar:4.1.0:compile
[INFO] +- com.jcraft:jsch.agentproxy.sshagent:jar:0.0.9:compile
[INFO] +- com.jcraft:jsch.agentproxy.usocket-jna:jar:0.0.9:compile
[INFO] +- junit:junit:jar:4.12:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] +- org.mockito:mockito-all:jar:1.10.19:test
[INFO] +- org.eclipse.jgit:org.eclipse.jgit:jar:5.0.2.201807311906-r:compile
[INFO] |  +- com.jcraft:jzlib:jar:1.1.1:compile
[INFO] |  +- com.googlecode.javaewah:JavaEWAH:jar:1.1.6:compile
[INFO] |  +- org.apache.httpcomponents:httpclient:jar:4.5.2:compile
[INFO] |  |  +- org.apache.httpcomponents:httpcore:jar:4.4.4:compile
[INFO] |  |  +- commons-logging:commons-logging:jar:1.2:compile
[INFO] |  |  \- commons-codec:commons-codec:jar:1.9:compile
[INFO] |  \- org.slf4j:slf4j-api:jar:1.7.2:compile
[INFO] +- org.slf4j:slf4j-simple:jar:1.7.2:test
[INFO] \- com.itemis.maven.plugins:unleash-scm-provider-api:jar:2.6.0:compile
[INFO]    +- javax.enterprise:cdi-api:jar:1.2:compile
[INFO]    |  +- javax.el:javax.el-api:jar:3.0.0:compile
[INFO]    |  +- javax.interceptor:javax.interceptor-api:jar:1.2:compile
[INFO]    |  \- javax.inject:javax.inject:jar:1:compile
[INFO]    +- org.apache.commons:commons-lang3:jar:3.4:compile
[INFO]    \- com.google.guava:guava:jar:19.0:compile

**Comment by shillner** [comment]
Seems like you don't have the latest sources checked out!
I added jsch as a project dependency to the git provider which enforces the usage of 1.54.

**Comment by andreasaronsson** [comment]
Indeed. Will verify as soon as I can.

**Comment by andreasaronsson** [comment]
New error

`
Caused by: org.eclipse.jgit.errors.TransportException: git@github.com:andreasaronsson/maven-plugins.git: There are not any available sig algorithm.
    at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession (JschConfigSessionFactory.java:183)
    at org.eclipse.jgit.transport.SshTransport.getSession (SshTransport.java:140)
    at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init> (TransportGitSsh.java:280)
    at org.eclipse.jgit.transport.TransportGitSsh.openFetch (TransportGitSsh.java:170)
    at org.eclipse.jgit.api.LsRemoteCommand.execute (LsRemoteCommand.java:200)
    at org.eclipse.jgit.api.LsRemoteCommand.call (LsRemoteCommand.java:161)
    at com.itemis.maven.plugins.unleash.scm.providers.ScmProviderGit.hasTag (ScmProviderGit.java:635)
    at com.itemis.maven.plugins.unleash.steps.actions.TagScm.rollback (TagScm.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
`

**Comment by shillner** [comment]
Sorry, not able to investigate this before October.
But please collect some more information about the error and the environment. It would also help if you could debug into the git provider until I'm back. 
Thanks ;) Freitag, 31 August 2018, 07:45nachm. +02:00 von Andreas Aronsson  notifications@github.com :

**Comment by andreasaronsson** [comment]
I checked my ~/.ssh/config and found `HostKeyAlgorithms ssh-rsa` which I have entered before to get unleash plugin working earlier with a gitlab instance. Removing that I get 
`Caused by: org.eclipse.jgit.api.errors.TransportException: git@github.com:andreasaronsson/maven-plugins.git: Auth fail`
and this could also be because of missing implementations of cryptographic algorithms would be my guess. 
Since the Jsch project does not seem to be as actively maintained anymore perhaps it would be interesting to investigate using sshj instead. But then I realized that it would require replacement of jgit as well.

**Comment by andreasaronsson** [comment]
This seems to point in the same direction https://github.com/zeapo/Android-Password-Store/issues/254

**Comment by andreasaronsson** [comment]
I got it to work (only tested with ecdsa key)

```
diff --git a/pom.xml b/pom.xml
index c94c08c..8caa898 100644
--- a/pom.xml
+++ b/pom.xml
@@ -10,7 +10,7 @@
 
   <groupId>com.itemis.maven.plugins</groupId>
   <artifactId>unleash-scm-provider-git</artifactId>
-  <version>2.2.1-SNAPSHOT</version>
+  <version>2.2.1</version>
 
   <name>Unleash SCM Provider Git</name>
   <description>The Git SCM provider for the Unleash Maven Plugin.</description>
@@ -40,13 +40,13 @@
 
   <properties>
     <version.java>1.6</version.java>
-    <version.jgit>5.0.2.201807311906-r</version.jgit>
-    <version.jsch>0.1.54</version.jsch>
+    <version.jgit>5.3.0.201903130848-r</version.jgit>
+    <version.jsch>0.1.55</version.jsch>
     <version.jsch-agentproxy>0.0.9</version.jsch-agentproxy>
     <version.junit>4.12</version.junit>
     <version.mockito-all>1.10.19</version.mockito-all>
-    <version.slf4j>1.7.2</version.slf4j>
-    <version.unleash-scm-provider-api>2.6.0</version.unleash-scm-provider-api>
+    <version.slf4j>1.7.25</version.slf4j>
+    <version.unleash-scm-provider-api>2.9.3</version.unleash-scm-provider-api>
   </properties>
 
   <dependencies>
@@ -119,4 +119,4 @@
       </plugins>
     </pluginManagement>
   </build>
-</project>
\ No newline at end of file
+</project>
diff --git a/src/main/java/com/itemis/maven/plugins/unleash/scm/providers/GitSshSessionFactory.java b/src/main/java/com/itemis/maven/plugins/unleash/scm/providers/GitSshSessionFactory.java
index c14a37c..6bbe8ee 100644
--- a/src/main/java/com/itemis/maven/plugins/unleash/scm/providers/GitSshSessionFactory.java
+++ b/src/main/java/com/itemis/maven/plugins/unleash/scm/providers/GitSshSessionFactory.java
@@ -110,6 +110,7 @@ class GitSshSessionFactory extends JschConfigSessionFactory {
       if (sshAgentConnector != null) {
         JSch.setConfig(PREFERRED_AUTHENTICATIONS, PUBLIC_KEY);
 
+        JSch.setLogger(new SimpleLogger());
         IdentityRepository identityRepository = new RemoteIdentityRepository(sshAgentConnector);
         jsch.setIdentityRepository(identityRepository);
       }
```

**Comment by MeyerNils** [comment]
Is there anything left to do or try here where I could support or is the only missing piece releasing a new version of this project now to have this usable with a non-SNAPSHOT dependency?

**Comment by andreasaronsson** [comment]
@MeyerNils hi fellow user! :-)
My guess is that it would help with testing and reporting the results here.
Other than that we have to wait until the maintainer can find the time to release I guess.

**Comment by MeyerNils** [comment]
Ok, did this. I build a local version version of unleash-scm-provider-git based on the current master and could successfully unleash my sample project with this version of the plugin. So if no other urgent things are open I think having a release of this state would be nice.

**Comment by scoldwell** [comment]
For those that don't want to or can't use a non-release build of the unleash plugin or providers, I was able to fix this in the plugin dependencies (thanks to @andreasaronsson's comment) like so:

      <plugin>
        <groupId>com.itemis.maven.plugins</groupId>
        <artifactId>unleash-maven-plugin</artifactId>
        <version>2.9.3</version>
        <dependencies>
          
          <dependency>
            <groupId>com.jcraft</groupId>
            <artifactId>jsch</artifactId>
            <version>0.1.55</version>
          </dependency>
          <dependency>
            <groupId>org.eclipse.jgit</groupId>
            <artifactId>org.eclipse.jgit</artifactId>
            <version>5.3.0.201903130848-r</version>
          </dependency>
          <dependency>
            <groupId>com.itemis.maven.plugins</groupId>
            <artifactId>unleash-scm-provider-api</artifactId>
            <version>2.9.3</version>
          </dependency>
          
          <dependency>
            <groupId>com.itemis.maven.plugins</groupId>
            <artifactId>unleash-scm-provider-git</artifactId>
            <version>2.2.0</version>
          </dependency>
        </dependencies>
        <configuration>
          <commitBeforeTagging>true</commitBeforeTagging>
        </configuration>
      </plugin>
