### ISSUE TITLE
Exception wrongly thrown on call to testConnection with empty repo

### ISSUE THREAD

**Issue by dhakehurst** [shillner/unleash-scm-provider-git#16]
- create an empty git repo.
- connect to it
- call testConnection
get 'ScmException' thrown

**Comment by MeyerNils** [comment]
Without giving it a try it looks for me that simply the exception text in the first case within [testConnection](https://github.com/shillner/unleash-scm-provider-git/blob/a534b88db8c7103b123deceb030beaee6df548fa/src/main/java/com/itemis/maven/plugins/unleash/scm/providers/ScmProviderGit.java#L140) is misleading.
